/**
 * /api/agents — admin-initiated agent management
 *
 * GET  /api/agents            list all agents (OWNER/ADMIN)
 * POST /api/agents            create new agent, return token ONCE
 *
 * DELETE handled in /api/agents/[id]/route.ts
 *
 * Auth model (new — admin-initiated):
 *   1. Admin clicks "Add Agent" in UI → POST /api/agents
 *   2. Server generates agentId + secretToken (32 bytes hex)
 *   3. Server returns BOTH ONCE — admin must copy to agent config
 *   4. Agent runs with config: { server_url, agent_id, secret_token }
 *   5. Agent heartbeats with HMAC(secret_token, body) using these creds
 *
 * The OLD self-registration flow (/api/agents/register with bootstrap token)
 * is kept as a deprecated fallback but the UI uses this endpoint.
 *
 * OWASP A01:2021 — only OWNER/ADMIN can create agents
 * OWASP A07:2021 — token shown ONCE, never recoverable from server
 */

import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { randomBytes } from "node:crypto";
import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/db";
import { encrypt } from "@/lib/security/crypto";
import { requireRole } from "@/lib/security/rbac";
import { audit } from "@/lib/security/audit";

export async function GET(_req: NextRequest) {
  const session = await requireRole("OWNER", "ADMIN");
  if (session instanceof NextResponse) return session;

  const agents = await prisma.agent.findMany({
    orderBy: [{ status: "asc" }, { lastHeartbeat: "desc" }],
    select: {
      id: true,
      name: true,
      hostname: true,
      ip: true,
      type: true,
      version: true,
      os: true,
      kernel: true,
      status: true,
      lastHeartbeat: true,
      lastError: true,
      registeredAt: true,
      revokedAt: true,
      eventsSent: true,
      _count: { select: { events: true } },
    },
  });

  // Compute effective status (stale/offline detection)
  const now = Date.now();
  const enriched = agents.map((a) => {
    let effective = a.status;
    if (a.status === "ONLINE" && a.lastHeartbeat) {
      const ageSec = (now - a.lastHeartbeat.getTime()) / 1000;
      if (ageSec > 600) effective = "OFFLINE";
      else if (ageSec > 120) effective = "STALE";
    }
    return { ...a, effectiveStatus: effective };
  });

  return NextResponse.json({ ok: true, agents: enriched });
}

const createSchema = z.object({
  name: z.string().min(1).max(128),
  type: z.enum(["BASH", "PYTHON"]),
  description: z.string().max(1024).optional(),
  // Optional default config — admin can pre-fill which logs the agent should watch
  defaultConfig: z
    .object({
      logs: z
        .array(
          z.object({
            path: z.string(),
            parser: z.string().default("syslog"),
          })
        )
        .optional(),
      fimPaths: z.array(z.string()).optional(),
      processWatchlist: z.array(z.string()).optional(),
      heartbeatIntervalSec: z.number().int().min(5).max(3600).optional(),
      eventBatchSize: z.number().int().min(1).max(1000).optional(),
    })
    .optional(),
});

export async function POST(req: NextRequest) {
  const session = await requireRole("OWNER", "ADMIN");
  if (session instanceof NextResponse) return session;
  const userId = session.userId;

  let body: z.infer<typeof createSchema>;
  try {
    body = createSchema.parse(await req.json());
  } catch (err) {
    return NextResponse.json(
      { error: "Invalid body", details: String(err) },
      { status: 400 }
    );
  }

  // Generate token: 32 bytes hex = 64 chars
  // Same entropy as INGEST_HMAC_SECRET.
  const secretToken = "os_agt_" + randomBytes(29).toString("hex");
  const secretEnc = encrypt(secretToken);

  const defaultConfig = body.defaultConfig ?? {
    logs: [
      { path: "/var/log/auth.log", parser: "sshd" },
      { path: "/var/log/syslog", parser: "syslog" },
    ],
    heartbeatIntervalSec: 30,
    eventBatchSize: 100,
  };

  const agent = await prisma.agent.create({
    data: {
      name: body.name,
      // agentId (id) auto-generated by Prisma cuid
      type: body.type,
      version: "0.0.0", // updated on first heartbeat
      status: "REGISTERED",
      secretEnc,
      config: defaultConfig as Prisma.InputJsonValue,
      // hostname/ip/os/kernel populated on first heartbeat
      eventsSent: 0,
    },
    select: { id: true, name: true, type: true, status: true, registeredAt: true },
  });

  await audit({
    userId,
    action: "agent.created",
    resourceType: "agent",
    resourceId: agent.id,
    metadata: {
      name: body.name,
      type: body.type,
      // Token prefix for audit trail (full token never logged)
      tokenPrefix: secretToken.slice(0, 12),
    },
  });

  // Return agentId + secretToken ONCE — admin must save it now.
  // After this response, the token is unrecoverable from the server.
  return NextResponse.json({
    ok: true,
    agent: {
      id: agent.id,
      name: agent.name,
      type: agent.type,
      status: agent.status,
      createdAt: agent.registeredAt,
    },
    // SHOWN ONCE — admin must copy this to agent config.
    credentials: {
      agentId: agent.id,
      secretToken,
      serverUrl: process.env.OPENSHIELD_PUBLIC_URL || "http://YOUR-SERVER:3001",
      setupHint:
        body.type === "BASH"
          ? "Save as agent_id + secret_token in /etc/openshield/agent.json"
          : "Save as agent_id + secret_token in /etc/openshield/agent.yaml",
    },
    warning:
      "Save these credentials NOW — the secret token cannot be recovered later. If lost, rotate it from the UI.",
  });
}
